<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="LeaveStatus.aspx.cs" Inherits="ep.LeaveStatus" %>
<asp:Content ID="Content1" ContentPlaceHolderID="abc" runat="server">
      <link href="css/bootstrap.min.css" rel="stylesheet" /> 
    <form id="form1" runat="server">
   

        <div>
    
         <div class="w3-card w3-round w3-white w3-center p-4">
        <div class="w3-container col-md-12 align-items-center p-4">
            
            <asp:GridView ID="GridView1" runat="server"  OnRowDeleting="OnRowDeleting"  AutoGenerateColumns="false" AllowPaging="true" 
                 OnPageIndexChanging="OnPaging" PageSize="6" CssClass="table table-striped table-bordered table-hover" AutoGenerateDeleteButton="true">
                <Columns>
                    <asp:BoundField ItemStyle-Width="150px" DataField="username" HeaderText="Employee Username " />
                    <asp:BoundField ItemStyle-Width="150px" DataField="Purpose" HeaderText="Purpose" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="StartDate" HeaderText="Start Date" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="EndDate" HeaderText="End Date" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="StatusNotif" HeaderText="Status" />

                    
                </Columns>
            </asp:GridView>
        </div>
      </div>
      <br/>
    </div>
    
   
    </form>
</asp:Content>
